quotes/urls.py
from django.urls import path

from . import views


app_name = 'quotes'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    # show quote
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    # functions: like, random quote
    path('<int:quote_id>/like/', views.like, name='like'),
    path('random/', views.rand_quote, name='random'),
    # create, update, delete
    path('add/', views.QuoteCreate.as_view(), name='add'),
    path('<int:pk>/edit/', views.QuoteUpdate.as_view(), name='edit'),
    path('<int:pk>/delete/', views.QuoteDelete.as_view(), name='delete'),
]

quotify/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    # was: 'quotes/'
    path('', include('quotes.urls')),
    path('admin/', admin.site.urls),
]

quotes/models.py
from django.db import models
from django.urls import reverse


class Quote(models.Model):
    quote_text = models.CharField(max_length=1000)
    pub_date = models.DateTimeField('date published', auto_now=True)
    likes = models.IntegerField(default=0)

    def __str__(self):
        return self.quote_text

    def get_absolute_url(self):
        """
        Absolute URL of a quote detail. Used for generic create/update views & model forms
        https://docs.djangoproject.com/en/3.0/topics/class-based-views/generic-editing/#model-forms
        """
        return reverse('quotes:detail', kwargs={'pk': self.pk})

quotes/views.py
import os
import json
import random

from django.http import HttpResponse, HttpResponseRedirect, Http404, JsonResponse
from django.shortcuts import get_object_or_404, render
from django.urls import reverse, reverse_lazy
from django.views import generic
from django.views.generic.edit import FormView, CreateView, DeleteView, UpdateView
from django.utils import timezone
from django.template import loader
from sendgrid import SendGridAPIClient
from sendgrid.helpers.mail import Mail

from .models import Quote


# functions
def send_email(msg):
    """Send email containing the message via sendgrid"""
    print(f"Trying to send email with msg: {msg}")
    # get destination address and API key from env vars
    dest_mail = os.getenv('EMAIL', None)
    api_key = os.environ.get('SENDGRID_API_KEY', None)
    if dest_mail is None or api_key is None:
        print("Env var 'EMAIL' or 'SENDGRID_API_KEY' missing. Can't send email.")
        return "Env var 'EMAIL' or 'SENDGRID_API_KEY' missing. Can't send email."

    email = Mail(from_email='hello@world.com', to_emails=dest_mail, subject='Quotify: Change Notification',
                 html_content=msg)
    try:
        sg = SendGridAPIClient(api_key=api_key)
        response = sg.send(email)
        print(f"Email response status code: {response.status_code}")
        return f"Sent email with msg: {msg} to {dest_mail}. Status code: {response.status_code}"
    except Exception as e:
        print(e.message)

def like(request, quote_id):
    """Like a specific quote"""
    # TODO: I should do this in a responsive manner in JS or Vue without page reload
    quote = get_object_or_404(Quote, pk=quote_id)
    quote.likes += 1
    quote.save()
    return HttpResponseRedirect(reverse('quotes:detail', args=(quote.id,)))


def rand_quote(request):
    """View a random quote"""
    rand_quote = random.choice(Quote.objects.all())
    # forward to detail view of randomly selected quote
    return HttpResponseRedirect(reverse('quotes:detail', args=(rand_quote.id,)))


# basic, gerenic views
class IndexView(generic.ListView):
    template_name = 'quotes/index.html'
    # instead of the default "object_list"
    context_object_name = 'quote_list'

    def get_queryset(self):
        """Return all quotes"""
        return Quote.objects.all().order_by('-pub_date')
        # TODO: trying to return json that I can then use with Vue.js; didn't work
        # wrap in list because QuerySet is not Json serializable
        # data = list(Quote.objects.values())
        # return JsonResponse(data, safe=False)


class DetailView(generic.DetailView):
    model = Quote
    template_name = 'quotes/detail.html'


# gerneric edit views
class QuoteCreate(CreateView):
    # default template for create & update: quotes/quote_form.html
    template_name = 'quotes/quote_form.html'
    model = Quote
    fields = ['quote_text']
    # object_change = send_email(f"New quote: {str(object)}")


class QuoteUpdate(UpdateView):
    model = Quote
    fields = ['quote_text']
    # object_change = send_email(f"Updated quote: {str(object)}")


class QuoteDelete(DeleteView):
    model = Quote
    success_url = reverse_lazy('quotes:index')

quotes/templates/quotes/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<!--    Bootstrap CSS: must come before any other CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.13.0/css/all.css" integrity="sha384-Bfad6CLCknfcloXFOyFnlgtENryhrpZCe29RTifKEixXQZ38WheV+i/6YWSzkz3V" crossorigin="anonymous">

    <title>Quotify</title>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light">
<!--        Branding and title -->
        <a class="navbar-brand" href="{% url 'quotes:index' %}">
            <i class="fas fa-quote-right"></i>
            Quotify
        </a>
<!--        Menu toggle button when collapsed -->
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
<!--        Menu -->
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'quotes:index' %}">All Quotes</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'quotes:random' %}">Random Quote</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'quotes:add' %}">New Quote</a>
                </li>
            </ul>
        </div>
    </nav>

    <div class="content container">
        {% block content %}
        {% endblock %}

        {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
    </div>

<!--    Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
</body>
</html>

quotes/templates/quotes/detail.html
{% extends 'quotes/base.html' %}

{% block content %}
    <h1>{{ quote.quote_text }}</h1>
    <p>Published on: {{ quote.pub_date }}</p>
<!--    <p><i class="fas fa-heart"></i>{{ quote.likes }} like{{ quote.likes |pluralize }}</p>-->
    <p>{{ quote.likes }} <i class="fas fa-heart"></i></p>

    <a class="btn btn-primary" href="{% url 'quotes:like' quote.id %}">Like <i class="fas fa-heart"></i></a>
    <a class="btn btn-secondary" href="{% url 'quotes:edit' quote.id %}">Edit <i class="fas fa-edit"></i></a>
    <a class="btn btn-danger" href="{% url 'quotes:delete' quote.id %}">Delete <i class="fas fa-trash"></i></a>

    <p></p>
    <p><a class="btn btn-light btn-block" href="{% url 'quotes:random' %}">Next Random Quote</a></p>

{% endblock %}

quotes/templates/quotes/index.html
{% extends 'quotes/base.html' %}

{% block content %}
    {% if quote_list %}
<!--    <script src="https://cdn.jsdelivr.net/npm/vue/dist/vue.js"></script>-->
<!--    <script type='text/javascript'>-->
<!--        var quotes = {{ quote_list|safe }};-->
<!--    </script>-->

<!--    <div id="app">-->
<!--        [[message]]-->

<!--        <ul>-->
<!--            <li v-for="quote in quotes">-->
<!--                [[ quote.quote_text ]]-->
<!--            </li>-->
<!--        </ul>-->
<!--    </div>-->

    <table class="table">
        <thead>
            <tr>
                <th scope="col">Publication Date</th>
                <th scope="col"><i class="fas fa-heart"></i></th>
                <th scope="col">Quote</th>
            </tr>
        </thead>
        <tbody>
            {% for quote in quote_list %}
            <tr>
                <td>{{ quote.pub_date }}</td>
                <td>{{ quote.likes }}</td>
                <td><a href="{% url 'quotes:detail' quote.id %}">{{ quote.quote_text }}</a></td>
            </tr>
            {% endfor %}
        </tbody>
    </table>

<!--    <script>-->
<!--        var app = new Vue({-->
<!--          delimiters: ['[[', ']]'],-->
<!--          el: '#app',-->
<!--          data: {-->
<!--              message: 'Hello Vue!',-->
<!--              people: people,-->
<!--          },-->
<!--          methods: {-->
<!--              greet: function(name) {-->
<!--                  console.log('Hello from ' + name + '!')-->
<!--              }-->
<!--          }-->
<!--        });-->
<!--      </script>-->
    {% else %}
        <p>No quotes available.</p>
    {% endif %}
{% endblock %}

quotes/templates/quotes/quote_confirm_delete.html
{% extends 'quotes/base.html' %}

{% block content %}
<form method="post">{% csrf_token %}
    <p>Are you sure you want to delete quote "{{ object }}"?</p>
    <input type="submit" value="Confirm">
</form>
{% endblock %}

quotes/templates/quotes/quote_form.html
{% extends 'quotes/base.html' %}

{% block content %}
    <form method="post">
        <!--        Django protects against Cross Site Request Forgeries. Should use the token below for all POST forms.-->
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Save">
    </form>
{% endblock %}